### ISSUE TITLE
how do I set the frame shift parameter? 

### ISSUE THREAD

**Issue by gemengtju** [r9y9/pyreaper#9]

**Comment by r9y9** [comment]
https://pyreaper.readthedocs.io/en/latest/generated/pyreaper.reaper.html#pyreaper.reaper

Please read the document. You can set `frame_period` parameter.

**Comment by gemengtju** [comment]
Yeah, I know the frame_period parameter. The frame_period is windows length, but we don't know the frame shift to determine the position of next frame.

**Comment by gemengtju** [comment]
Can I set the frame shift to half of the frame length (frame_period parameter), and could you help me how to set it? because the parameters in the document are limited.

**Comment by r9y9** [comment]
frame_period is not window length (to be specific, https://github.com/google/REAPER/blob/a3926d3c256bcdc500e7b524ebed56c05a5fbc3a/epoch_tracker_main.cc#L45) and I'm not sure why you are talking about frame length even if REAPER doesn't expose such a parameter. I'm not sure if frame length makes sense for REAPER, because some of pitch estimation algorithms use pitch adaptive variable window length (e.g. WORLD).

You should probably ask https://github.com/google/REAPER instead, as the pyreaper is just a wrapper around it, but I'd recommend you to take a look at REAPER’s README and code.

**Comment by gemengtju** [comment]
ok,thx. So I think the frame_period parameter (or the option -e in ttps://github.com/google/REAPER) is equivalent to frame_shift. If the frame_period parameter is determined, the number of frames in a utterance is determined. And we also know the pitch value of each frame, right?
